server:
  port: 8080

spring:
  rabbitmq:
    host: rabbitmq-cooperativismo
    port: 5672
    username: mqadmin
    password: Admin123XX_
    connection-timeout: 15000
  application:
    name: cooperativismo-service
  datasource:
    url: jdbc:mysql://db-cooperativismo.cxob2899jciy.us-east-2.rds.amazonaws.com/cooperativismo_db3?useSSL=false&serverTimezone=UTC&createDatabaseIfNotExist=true
    username: admin
    password: cooperativismo1232021
  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        enable_lazy_load_no_trans: true
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect

springdoc:
  api-docs:
    path: '/api-docs'
  swagger-ui:
    path: '/swagger-ui-custom.html'

queue:
  session-ended:
    name: votingSessionEndedQueue